"""UDS (ISO 14229-1) service identifiers and common subfunction constants."""

from __future__ import annotations

from enum import IntEnum

POSITIVE_RESPONSE_OFFSET = 0x40
NEGATIVE_RESPONSE_SID = 0x7F


class Service(IntEnum):
    DIAGNOSTIC_SESSION_CONTROL = 0x10
    ECU_RESET = 0x11
    CLEAR_DIAGNOSTIC_INFORMATION = 0x14
    READ_DTC_INFORMATION = 0x19
    READ_DATA_BY_IDENTIFIER = 0x22
    READ_MEMORY_BY_ADDRESS = 0x23
    SECURITY_ACCESS = 0x27
    COMMUNICATION_CONTROL = 0x28
    READ_DATA_BY_PERIODIC_ID = 0x2A
    DYNAMICALLY_DEFINE_DATA_ID = 0x2C
    WRITE_DATA_BY_IDENTIFIER = 0x2E
    INPUT_OUTPUT_CONTROL = 0x2F
    ROUTINE_CONTROL = 0x31
    REQUEST_DOWNLOAD = 0x34
    REQUEST_UPLOAD = 0x35
    TRANSFER_DATA = 0x36
    REQUEST_TRANSFER_EXIT = 0x37
    WRITE_MEMORY_BY_ADDRESS = 0x3D
    TESTER_PRESENT = 0x3E
    CONTROL_DTC_SETTING = 0x85


class Session(IntEnum):
    DEFAULT = 0x01
    PROGRAMMING = 0x02
    EXTENDED_DIAGNOSTIC = 0x03
    SAFETY_SYSTEM_DIAGNOSTIC = 0x04


class ResetType(IntEnum):
    HARD_RESET = 0x01
    KEY_OFF_ON_RESET = 0x02
    SOFT_RESET = 0x03


class RoutineControlType(IntEnum):
    START = 0x01
    STOP = 0x02
    REQUEST_RESULTS = 0x03


class DtcReportType(IntEnum):
    REPORT_NUMBER_BY_STATUS_MASK = 0x01
    REPORT_DTC_BY_STATUS_MASK = 0x02
    REPORT_DTC_SNAPSHOT_RECORD = 0x04
    REPORT_DTC_EXTENDED_DATA_RECORD = 0x06
    REPORT_SUPPORTED_DTC = 0x0A


# DTC status bit masks (ISO 14229-1 Annex D).
class DtcStatus(IntEnum):
    TEST_FAILED = 0x01
    TEST_FAILED_THIS_CYCLE = 0x02
    PENDING = 0x04
    CONFIRMED = 0x08
    TEST_NOT_COMPLETE_SINCE_CLEAR = 0x10
    TEST_FAILED_SINCE_CLEAR = 0x20
    TEST_NOT_COMPLETE_THIS_CYCLE = 0x40
    WARNING_INDICATOR_REQUESTED = 0x80


SUPPRESS_POSITIVE_RESPONSE = 0x80  # OR into a subfunction byte to suppress the positive ack
