// Writes supabase/seed/seed_content.sql (for anyone with psql access). Prefer scripts/seed.mjs.
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { loadContent, root } from './content.mjs'

const TAG = '$mw$'
const q = (s) => { const str = String(s ?? ''); if (str.includes(TAG)) throw new Error('content contains dollar tag'); return `${TAG}${str}${TAG}` }
const arr = (a) => `array[${(a ?? []).map((x) => q(x)).join(',')}]::text[]`
const { categories, articles } = loadContent()
const lines = ['-- Generated by scripts/build-seed.mjs. Do not edit by hand; edit content/ instead.', 'begin;']
for (const c of categories) lines.push(
  `insert into public.mw_categories (slug, name, description, icon, sort_order) values (${q(c.slug)}, ${q(c.name)}, ${q(c.description)}, ${q(c.icon)}, ${c.sort_order ?? 100})
  on conflict (slug) do update set name = excluded.name, description = excluded.description, icon = excluded.icon, sort_order = excluded.sort_order;`)
for (const a of articles) lines.push(
  `insert into public.mw_articles (slug, title, summary, body, kind, category_id, tags, manufacturer, model_numbers, source, status)
  values (${q(a.slug)}, ${q(a.title)}, ${q(a.summary)}, ${q(a.body)}, ${q(a.kind)}, (select id from public.mw_categories where slug = ${q(a.category)}),
          ${arr(a.tags)}, ${q(a.manufacturer)}, ${arr(a.model_numbers)}, ${q(a.source)}, 'published')
  on conflict (slug) do update set title = excluded.title, summary = excluded.summary, body = excluded.body, kind = excluded.kind,
          category_id = excluded.category_id, tags = excluded.tags, manufacturer = excluded.manufacturer,
          model_numbers = excluded.model_numbers, source = excluded.source, status = 'published';`)
lines.push('commit;')
const out = join(root, 'supabase', 'seed', 'seed_content.sql')
writeFileSync(out, lines.join('\n\n') + '\n')
console.log(`wrote ${out}: ${categories.length} categories, ${articles.length} articles`)
