// Writes supabase/seed/seed_content.sql (for anyone with psql access). Prefer scripts/seed.mjs.
import { writeFileSync, existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { loadContent, root } from './content.mjs'

const TAG = '$mw$'
const q = (s) => { const str = String(s ?? ''); if (str.includes(TAG)) throw new Error('content contains dollar tag'); return `${TAG}${str}${TAG}` }
const arr = (a) => `array[${(a ?? []).map((x) => q(x)).join(',')}]::text[]`
const { categories, articles } = loadContent()

// Rule: every article ships with at least one visual aid, and every referenced image must exist in public/img.
// Diagrams are generated by scripts/diagrams (node scripts/diagrams/run.mjs) and placed by scripts/add-figures.mjs.
const credits = existsSync(join(root, 'public', 'photos', 'credits.json')) ? JSON.parse(readFileSync(join(root, 'public', 'photos', 'credits.json'), 'utf8')) : {}
const problems = []
for (const a of articles) {
  const refs = [...String(a.body).matchAll(/\]\(\/img\/([^)\s]+)\)/g)].map((m) => m[1])
  if (refs.length === 0 && !/\]\(\/photos\//.test(String(a.body))) problems.push(`${a.slug}: no figure (add a diagram under public/img and a ![alt](/img/...) reference)`)
  for (const r of refs) if (!existsSync(join(root, 'public', 'img', r))) problems.push(`${a.slug}: missing image public/img/${r}`)
  const photos = [...String(a.body).matchAll(/\]\(\/photos\/([^)\s]+)\)/g)].map((m) => m[1])
  for (const ph of photos) {
    if (!existsSync(join(root, 'public', 'photos', ph))) problems.push(`${a.slug}: missing photo public/photos/${ph}`)
    else if (!credits[ph]) problems.push(`${a.slug}: photo ${ph} has no entry in public/photos/credits.json`)
  }
}
if (problems.length) { console.error('Figure check failed:\n' + problems.join('\n')); process.exit(1) }
const lines = ['-- Generated by scripts/build-seed.mjs. Do not edit by hand; edit content/ instead.', 'begin;']
for (const c of categories) lines.push(
  `insert into public.mw_categories (slug, name, description, icon, sort_order) values (${q(c.slug)}, ${q(c.name)}, ${q(c.description)}, ${q(c.icon)}, ${c.sort_order ?? 100})
  on conflict (slug) do update set name = excluded.name, description = excluded.description, icon = excluded.icon, sort_order = excluded.sort_order;`)
for (const a of articles) lines.push(
  `insert into public.mw_articles (slug, title, summary, body, kind, category_id, tags, manufacturer, model_numbers, source, status)
  values (${q(a.slug)}, ${q(a.title)}, ${q(a.summary)}, ${q(a.body)}, ${q(a.kind)}, (select id from public.mw_categories where slug = ${q(a.category)}),
          ${arr(a.tags)}, ${q(a.manufacturer)}, ${arr(a.model_numbers)}, ${q(a.source)}, 'published')
  on conflict (slug) do update set title = excluded.title, summary = excluded.summary, body = excluded.body, kind = excluded.kind,
          category_id = excluded.category_id, tags = excluded.tags, manufacturer = excluded.manufacturer,
          model_numbers = excluded.model_numbers, source = excluded.source, status = 'published';`)
lines.push('commit;')
const out = join(root, 'supabase', 'seed', 'seed_content.sql')
writeFileSync(out, lines.join('\n\n') + '\n')
console.log(`wrote ${out}: ${categories.length} categories, ${articles.length} articles`)
